/* eslint-disable import/prefer-default-export */

// router
export const CHANGE_ROUTE = 'CHANGE_ROUTE';
export const GO_BACK = 'GO_BACK';

// firebase
export const FIREBASE_LOAD = 'FIREBASE_LOAD';
export const FIREBASE_LOGIN_SUCESS = 'FIREBASE_LOGIN_SUCESS';
export const FIREBASE_ERROR = 'FIREBASE_ERROR';
export const FIREBASE_CREATE_SUCCESS = 'FIREBASE_CREATE_SUCCESS';
export const FIREBASE_READ_SUCCESS = 'FIREBASE_READ_SUCCESS';
export const FIREBASE_UPDATE_SUCCESS = 'FIREBASE_UPDATE_SUCCESS';
export const FIREBASE_DELETE_SUCCESS = 'FIREBASE_DELETE_SUCCESS';
export const FIREBASE_SAVE_LOCAL_FILE = 'FIREBASE_SAVE_LOCAL_FILE';
export const FIREBASE_SUBSCRIBE = 'FIREBASE_SUBSCRIBE';
export const FIREBASE_UNSUBSCRIBE = 'FIREBASE_UNSUBSCRIBE';


// app
export const CONNECT_USER = 'CONNECT_USER';
export const DISCONNECT_USER = 'DISCONNECT_USER';
export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';
